---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package: 
      name:
        - python3-psutil
        - htop
        - tmux
        - vim-nox
        - dstat
        - sysstat

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/wos/.bashrc
      owner: wos
      group: wos

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/thewosca/ansible_desktop.git
