---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package: 
      name:
        - python3-psutil
        - htop
        - tmux
        - vim-nox
        - dstat
        - sysstat

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: wos
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: wos
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"




